-- Initial Seed Data for Echoes
-- Inserts initial characters and canonical scenes for the story-oriented launch

-- Characters
INSERT INTO characters (id, slug, name, description, avatar_url, category, tags, sort_order, is_active, is_featured) VALUES
(gen_random_uuid(), 'david', 'David', 'King David, the psalmist and shepherd-king whose life spans joy, struggle, and faith.', NULL, 'Old Testament', '["warrior", "poet", "king"]'::JSONB, 1, true, true),
(gen_random_uuid(), 'esther', 'Esther', 'Queen Esther, courageous and wise, who stepped into a dangerous palace story to save her people.', NULL, 'Old Testament', '["queen", "courage", "heart"]'::JSONB, 2, true, true),
(gen_random_uuid(), 'paul', 'Paul', 'Apostle Paul, the missionary thinker whose journeys shaped the early church narrative.', NULL, 'New Testament', '["apostle", "missionary", "teacher"]'::JSONB, 3, true, true);

-- Canonical scenes for David
INSERT INTO scenes (id, character_id, slug, title, description, intro_text, prompt_template, thumbnail_url, mood_tags, difficulty_level, access_tier, is_public_browse, is_active, sort_order) VALUES
(gen_random_uuid(), (SELECT id FROM characters WHERE slug = 'david'), 'david-shepherds-watch', 'Shepherd''s Watch', 'Stand with David as he guards the flock at dusk and hears the first stirrings of a destiny beyond the hillside.', 'The sun is low, the sheep are restless, and a new sense of calling rises. Choose how David answers the stirring in his heart.', 'Scene orchestration: place the user on the hilltop at sunset, describe the flock and the quiet tension, and let David respond to inner conviction.', NULL, '["pastoral", "intimate", "origin"]'::JSONB, 2, 'free', true, true, 1),
(gen_random_uuid(), (SELECT id FROM characters WHERE slug = 'david'), 'david-ark-return', 'Ark''s Return', 'Join David as he leads the ark into Jerusalem, balancing triumph with the fragile weight of national hope.', 'The streets are alive with music and prayer. Guide David as he decides what to honor first: the people, the Lord, or the promise of a new kingdom.', 'Scene orchestration: open with the procession into the city, describe the sacred tension, and let David shape the moment by choosing the story''s tone.', NULL, '["ceremonial", "joyful", "weighty"]'::JSONB, 4, 'premium', false, true, 2);

-- Canonical scenes for Esther
INSERT INTO scenes (id, character_id, slug, title, description, intro_text, prompt_template, thumbnail_url, mood_tags, difficulty_level, access_tier, is_public_browse, is_active, sort_order) VALUES
(gen_random_uuid(), (SELECT id FROM characters WHERE slug = 'esther'), 'esther-palace-entrance', 'Palace Entrance', 'Follow Esther as she enters the palace and senses the strange blend of danger and opportunity that will define her path.', 'The court is ornate and every glance carries meaning. Help Esther decide how much to observe before speaking.', 'Scene orchestration: place the user among the palace corridors, describe the watchful eyes and the pressure of promise, then let Esther''s first choice shape her journey.', NULL, '["royal", "fraught", "poised"]'::JSONB, 2, 'free', true, true, 1),
(gen_random_uuid(), (SELECT id FROM characters WHERE slug = 'esther'), 'esther-king-supper', 'The King''s Supper', 'Enter the tense banquet where Esther invites the king and the hidden threat to her people comes into clear focus.', 'The hall is set, the king is watching, and a single word can change everything. Help Esther choose how she reveals the truth.', 'Scene orchestration: place the user in the banquet room, emphasize the stakes, and let Esther balance fear, faith, and strategy.', NULL, '["tense", "courageous", "strategic"]'::JSONB, 4, 'premium', false, true, 2);

-- Canonical scenes for Paul
INSERT INTO scenes (id, character_id, slug, title, description, intro_text, prompt_template, thumbnail_url, mood_tags, difficulty_level, access_tier, is_public_browse, is_active, sort_order) VALUES
(gen_random_uuid(), (SELECT id FROM characters WHERE slug = 'paul'), 'paul-road-damascus', 'Road to Damascus', 'Ride with Paul as the sky flashes and a life of certainty collides with an impossible revelation.', 'A bright light falls around you, and a voice asks why you persecute it. Choose how Paul responds in the moment of crisis.', 'Scene orchestration: begin on a dusty road, describe the sudden light and the inner turmoil, then let Paul shape his response to the supernatural voice.', NULL, '["dramatic", "transformative", "urgent"]'::JSONB, 3, 'free', true, true, 1),
(gen_random_uuid(), (SELECT id FROM characters WHERE slug = 'paul'), 'paul-athens-debate', 'Athens Debate', 'Step into the Agora with Paul as he speaks to philosophers and feels the tension between faith and reason.', 'The city hums with questions. Help Paul choose the thread that makes the message both clear and unforgettable.', 'Scene orchestration: establish the marble forum and the curious crowd, then let Paul respond with conviction and clarity.', NULL, '["philosophical", "public", "inspiring"]'::JSONB, 5, 'premium', false, true, 2);